# Generated by Django 6.0.2 on 2026-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='full_conversation_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
